// Generated by gencpp from file practicas/tipo_servicioRequest.msg
// DO NOT EDIT!


#ifndef PRACTICAS_MESSAGE_TIPO_SERVICIOREQUEST_H
#define PRACTICAS_MESSAGE_TIPO_SERVICIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace practicas
{
template <class ContainerAllocator>
struct tipo_servicioRequest_
{
  typedef tipo_servicioRequest_<ContainerAllocator> Type;

  tipo_servicioRequest_()
    : argumento1(0)
    , argumento2(0)  {
    }
  tipo_servicioRequest_(const ContainerAllocator& _alloc)
    : argumento1(0)
    , argumento2(0)  {
  (void)_alloc;
    }



   typedef int64_t _argumento1_type;
  _argumento1_type argumento1;

   typedef int64_t _argumento2_type;
  _argumento2_type argumento2;





  typedef boost::shared_ptr< ::practicas::tipo_servicioRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::practicas::tipo_servicioRequest_<ContainerAllocator> const> ConstPtr;

}; // struct tipo_servicioRequest_

typedef ::practicas::tipo_servicioRequest_<std::allocator<void> > tipo_servicioRequest;

typedef boost::shared_ptr< ::practicas::tipo_servicioRequest > tipo_servicioRequestPtr;
typedef boost::shared_ptr< ::practicas::tipo_servicioRequest const> tipo_servicioRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::practicas::tipo_servicioRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::practicas::tipo_servicioRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace practicas

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'practicas': ['/home/kevin/catkin_ws/src/practicas/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::practicas::tipo_servicioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::practicas::tipo_servicioRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::practicas::tipo_servicioRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe55b827825314c8772a6284d89fd50a";
  }

  static const char* value(const ::practicas::tipo_servicioRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe55b827825314c8ULL;
  static const uint64_t static_value2 = 0x772a6284d89fd50aULL;
};

template<class ContainerAllocator>
struct DataType< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "practicas/tipo_servicioRequest";
  }

  static const char* value(const ::practicas::tipo_servicioRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 argumento1\n\
int64 argumento2\n\
";
  }

  static const char* value(const ::practicas::tipo_servicioRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.argumento1);
      stream.next(m.argumento2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tipo_servicioRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::practicas::tipo_servicioRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::practicas::tipo_servicioRequest_<ContainerAllocator>& v)
  {
    s << indent << "argumento1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.argumento1);
    s << indent << "argumento2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.argumento2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRACTICAS_MESSAGE_TIPO_SERVICIOREQUEST_H
