// Generated by gencpp from file practicas/tipo_servicio.msg
// DO NOT EDIT!


#ifndef PRACTICAS_MESSAGE_TIPO_SERVICIO_H
#define PRACTICAS_MESSAGE_TIPO_SERVICIO_H

#include <ros/service_traits.h>


#include <practicas/tipo_servicioRequest.h>
#include <practicas/tipo_servicioResponse.h>


namespace practicas
{

struct tipo_servicio
{

typedef tipo_servicioRequest Request;
typedef tipo_servicioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct tipo_servicio
} // namespace practicas


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::practicas::tipo_servicio > {
  static const char* value()
  {
    return "a979325dbca13dacf90a487ef6a5bb09";
  }

  static const char* value(const ::practicas::tipo_servicio&) { return value(); }
};

template<>
struct DataType< ::practicas::tipo_servicio > {
  static const char* value()
  {
    return "practicas/tipo_servicio";
  }

  static const char* value(const ::practicas::tipo_servicio&) { return value(); }
};


// service_traits::MD5Sum< ::practicas::tipo_servicioRequest> should match 
// service_traits::MD5Sum< ::practicas::tipo_servicio > 
template<>
struct MD5Sum< ::practicas::tipo_servicioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::practicas::tipo_servicio >::value();
  }
  static const char* value(const ::practicas::tipo_servicioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::practicas::tipo_servicioRequest> should match 
// service_traits::DataType< ::practicas::tipo_servicio > 
template<>
struct DataType< ::practicas::tipo_servicioRequest>
{
  static const char* value()
  {
    return DataType< ::practicas::tipo_servicio >::value();
  }
  static const char* value(const ::practicas::tipo_servicioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::practicas::tipo_servicioResponse> should match 
// service_traits::MD5Sum< ::practicas::tipo_servicio > 
template<>
struct MD5Sum< ::practicas::tipo_servicioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::practicas::tipo_servicio >::value();
  }
  static const char* value(const ::practicas::tipo_servicioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::practicas::tipo_servicioResponse> should match 
// service_traits::DataType< ::practicas::tipo_servicio > 
template<>
struct DataType< ::practicas::tipo_servicioResponse>
{
  static const char* value()
  {
    return DataType< ::practicas::tipo_servicio >::value();
  }
  static const char* value(const ::practicas::tipo_servicioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRACTICAS_MESSAGE_TIPO_SERVICIO_H
