// Generated by gencpp from file holamundo/IoTSensor.msg
// DO NOT EDIT!


#ifndef HOLAMUNDO_MESSAGE_IOTSENSOR_H
#define HOLAMUNDO_MESSAGE_IOTSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace holamundo
{
template <class ContainerAllocator>
struct IoTSensor_
{
  typedef IoTSensor_<ContainerAllocator> Type;

  IoTSensor_()
    : id(0)
    , region()
    , temperatura(0.0)
    , humedad(0.0)  {
    }
  IoTSensor_(const ContainerAllocator& _alloc)
    : id(0)
    , region(_alloc)
    , temperatura(0.0)
    , humedad(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _region_type;
  _region_type region;

   typedef float _temperatura_type;
  _temperatura_type temperatura;

   typedef float _humedad_type;
  _humedad_type humedad;





  typedef boost::shared_ptr< ::holamundo::IoTSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::holamundo::IoTSensor_<ContainerAllocator> const> ConstPtr;

}; // struct IoTSensor_

typedef ::holamundo::IoTSensor_<std::allocator<void> > IoTSensor;

typedef boost::shared_ptr< ::holamundo::IoTSensor > IoTSensorPtr;
typedef boost::shared_ptr< ::holamundo::IoTSensor const> IoTSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::holamundo::IoTSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::holamundo::IoTSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace holamundo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'holamundo': ['/home/kevin/catkin_ws/src/holamundo/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::holamundo::IoTSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::holamundo::IoTSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::holamundo::IoTSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::holamundo::IoTSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::holamundo::IoTSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::holamundo::IoTSensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::holamundo::IoTSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bc380b2aacba9ecd7c71cb52d71dc748";
  }

  static const char* value(const ::holamundo::IoTSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbc380b2aacba9ecdULL;
  static const uint64_t static_value2 = 0x7c71cb52d71dc748ULL;
};

template<class ContainerAllocator>
struct DataType< ::holamundo::IoTSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "holamundo/IoTSensor";
  }

  static const char* value(const ::holamundo::IoTSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::holamundo::IoTSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
string region\n\
float32 temperatura\n\
float32 humedad\n\
";
  }

  static const char* value(const ::holamundo::IoTSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::holamundo::IoTSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.region);
      stream.next(m.temperatura);
      stream.next(m.humedad);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IoTSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::holamundo::IoTSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::holamundo::IoTSensor_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "region: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.region);
    s << indent << "temperatura: ";
    Printer<float>::stream(s, indent + "  ", v.temperatura);
    s << indent << "humedad: ";
    Printer<float>::stream(s, indent + "  ", v.humedad);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HOLAMUNDO_MESSAGE_IOTSENSOR_H
